version: '3.1'

services:
  db:
    container_name: imageuploader-db
    image: 'postgres:14.2-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: IMAGEUPLOADER